#!/usr/local/bin/zsh

# stuff for every os
alias add-key='ssh-add $HOME/.ssh/id_dsa'

alias cd..="cd .."
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."
alias /="cd /"

alias md="mkdir"
alias rd="rmdir"
alias cls="clear"
alias d='dirs -v'
alias j='jobs -l'
alias s='screen -DR'
alias h='history'
alias x='startx &; logout'
alias f='find . -name'
alias e='emacsclient -n'

alias rot13="tr '[A-Za-z]' '[N-ZA-Mn-za-m]'"

# ls command
if [[ $OSNAME = "FreeBSD" || $OSNAME = "Darwin" ]]; then
	LSCOLOROPT='-G'
elif [[ $OSNAME = "Linux" || $OSNAME = "cygwin" || $OSNAME = "CYGWIN_NT-5.1" ]]; then
	LSCOLOROPT='--color=auto'
fi
alias ll="ls -lhF $LSCOLOROPT"
alias la="command ls -lhFa $LSCOLOROPT"
alias lf="command ls -F $LSCOLOROPT"
alias dir="command ls -AlF $LSCOLOROPT"
alias l="command ls -AsF $LSCOLOROPT"

# BitKeeper nicers
#alias bkst="bk sfiles -cx | sed 's/SCCS\/s\.//'"
alias bkst="bk sfiles -cgvx"

# random junk
alias longmont-library='telnet 204.133.207.247'

if [[ $OSTYPE = "cygwin" ]]; then
	if [[ $? = 0 ]]; then
		gvim () { \
            findcscopeout
            if [[ "z$*" = "z" ]] ; then \
                nohup \gvim > /dev/null 2>&1 & ; \
            else  \
                nohup \gvim `cygpath -m -- $*` > /dev/null 2>&1 & ;\
            fi \
        }
	fi
    alias start="cmd /c start"
    alias open="cmd /c start"
    deltree () { \
        for f in $* ; do\
            if [[ -d "$f" ]]; then
                echo "Removing $f..." ; \
                time cmd /c "rd /s /q `cygpath -w $f`" ; \
            elif [[ -f "$f" ]]; then \
                echo "Removing $f..." ; \
                cmd /c "del /f /q `cygpath -w $f`" ; \
            fi \
        done \
    }
    packdir() { \
        for f in $* ; do\
            if [[ -d "$f" ]]; then
                echo "Packing $f..." ; \
                time compact /c "`cygpath -w $f`" ; \
                time compact /c /a /i /s "`cygpath -w $f`\\\*" ; \
            elif [[ -f "$f" ]]; then \
                echo "Packing $f..." ; \
                compact /c /i /a "`cygpath -w $f`" ; \
            fi \
        done \
    }
    unpackdir() { \
        for f in $* ; do\
            if [[ -d "$f" ]]; then
                echo "Unpacking $f..." ; \
                time compact /u "`cygpath -w $f`" ; \
                time compact /u /a /i /s "`cygpath -w $f`\\\*" ; \
            elif [[ -f "$f" ]]; then \
                echo "Unpacking $f..." ; \
                compact /u /i /a "`cygpath -w $f`" ; \
            fi \
        done \
    }
else
    if [[ $OSNAME = "Darwin" ]]; then
        alias start="open"
        gvim () {
            findcscopeout
            nohup mvim $* > /dev/null 2>&1 &
        }
    else
        alias start="xdg-open"
        gvim () {
            findcscopeout
            nohup \gvim --servername `hostname` $* > /dev/null 2>&1 &
        }
    fi
    deltree () { \
        for f in $* ; do\
            if [[ -d "$f" ]]; then
                echo "Removing $f..." ; \
                time rm -rf "$f" ; \
            elif [[ -f "$f" ]]; then \
                echo "Removing $f..." ; \
                rm -f "$f" ; \
            fi \
        done \
    }
fi

# Always open files in the same instance of GVim
alias ed="gvim --remote-tab"

switchenv () {
    `$HOME/.zsh/scripts/switchenv.pl $1`
}

# Try to find cscope.out, and set the CSCOPE_DB variable
findcscopeout() {
    TRYDIR=`pwd`
    while [ "$TRYDIR" != "/" -a "$TRYDIR" != "" ] ; do
        #    echo "$TRYDIR"
        if [ -e "$TRYDIR/cscope.out" ] ; then
            if [ $OSTYPE = "cygwin" ]; then
                export CSCOPE_DB=`cygpath -m $TRYDIR/cscope.out`
            else
                export CSCOPE_DB=$TRYDIR/cscope.out
            fi
            break
        fi
        TRYDIR=`dirname $TRYDIR`
    done
    echo "Using CSCOPE database: $CSCOPE_DB"
}
