#!/usr/local/bin/zsh

# Use Emacs style key bindings
bindkey -e

# PgUp - Search History previous
bindkey -e '[5~'  'history-beginning-search-backward'
# PgDown - Search History next
bindkey -e '[6~'  'history-beginning-search-forward'
# ^P - Push the current command and start a new command
bindkey -e ^p  push-line-or-edit
