(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(ecb-options-version "2.32")
 '(ecb-source-path (quote (("~/src/devalot" "Devalot") ("~/src/getreal" "GetReal") ("~/ssrc/cov/stsweb" "STSWeb"))))
 '(ecb-wget-setup (quote cons)))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(default ((t (:background "#191919" :foreground "#FFFFFF"))))
 '(bm-fringe-face ((t (:foreground "#ff8e43"))))
 '(compilation-error ((t (:background "sienna4" :bold t))))
 '(compilation-info ((t (:inherit (quote font-lock-string-face) :bold t))))
 '(compilation-line-number ((t (:foreground "#FF6666" :bold t))))
 '(completion-dynamic-face ((t (:inherit (quote match)))))
 '(diff-added ((t (:foreground "#d7ffaf"))))
 '(diff-changed ((t (:foreground "#ffc28d"))))
 '(diff-context ((t (:foreground "#888888"))))
 '(diff-indicator-added ((t (:background "#d7ffaf" :foreground "#000000"))))
 '(diff-indicator-chnaged ((t (:background "#ffc28d" :foreground "#000000"))))
 '(diff-indicator-removed ((t (:background "#ff9999" :foreground "#000000"))))
 '(diff-removed ((t (:foreground "#ff9999"))))
 '(ecb-default-highlight-face ((t (:background "#A5F26E" :foreground "#000000"))))
 '(elscreen-tab-background-face ((t (:background "#787878" :box (:line-width 1 :style released-button)))))
 '(elscreen-tab-current-screen-face ((t (:background "#969696" :foreground "#000000" :height 1.1 :inherit variable-pitch))))
 '(elscreen-tab-other-screen-face ((t (:background "#787878" :foreground "#444444" :height 1.1 :inherit variable-pitch))))
 '(erb-comment-delim-face ((t (:foreground "#B150E7" :background "grey15"))))
 '(erb-comment-face ((t (:italic t :foreground "#B150E7" :background "grey15"))))
 '(erb-delim-face ((t (:foreground "#FFAEEA" :background "grey15"))))
 '(erb-face ((t (:background "grey15"))))
 '(erb-out-delim-face ((t (:foreground "#FFAEEA" :background "grey15"))))
 '(erb-out-face ((t (:background "grey15"))))
 '(flymake-errline ((t :underline "red")))
 '(flymake-warnline ((t :underline "green")))
 '(font-lock-builtin-face ((t (:foreground "#59ACC2"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#888888"))))
 '(font-lock-comment-face ((t (:italic t :foreground "#B150E7"))))
 '(font-lock-constant-face ((t (:foreground "#6BCFF7"))))
 '(font-lock-function-name-face ((t (:bold t :foreground "#E8BF6A"))))
 '(font-lock-keyword-face ((t (:bold t :foreground "#CC7832"))))
 '(font-lock-preprocessor-face ((t (:background "#202020"))))
 '(font-lock-string-face ((t (:foreground "#A5F26E"))))
 '(font-lock-type-face ((t (:bold t :foreground "#8888ff"))))
 '(font-lock-variable-name-face ((t (:foreground "#D0D0F3"))))
 '(font-lock-warning-face ((t (:underline "red"))))
 '(highlight ((t (:inherit (quote match)))))
 '(hl-line ((t :background "#000000" :underline "#444444" :bold t)))
 '(ido-first-match ((t (:inherit (quote font-lock-string-face)))))
 '(ido-subdir ((t (:inherit (quote font-lock-function-name-face)))))
 '(magit-branch ((t (:foreground "#E07BE0"))))
 '(magit-diff-add ((t (:inherit (quote diff-added)))))
 '(magit-diff-del ((t (:inherit (quote diff-removed)))))
 '(magit-diff-file-header ((t (:inherit (quote font-lock-constant-face)))))
 '(magit-diff-hunk-header ((t (:inherit (quote font-lock-keyword-face)))))
 '(magit-diff-none ((t (:inherit (quote font-lock-comment-delimiter-face)))))
 '(magit-header ((t (:inherit (quote org-level-1)))))
 '(magit-item-highlight ((t (:background "#000000"))))
 '(match ((t :background "#4A6152")))
 '(minibuffer-noticeable-prompt ((t (:inherit (quote font-lock-builtin-face) :bold t))))
 '(mode-line ((t (:background "DarkRed" :foreground "white" :box (:line-width 1 :style released-button)))))
 '(mode-line-buffer-id ((t (:background "DarkRed" :foreground "white"))))
 '(mode-line-inactive ((t (:background "#4D4D4D" :foreground "#FFFFFF" :box (:line-width 1 :style released-button)))))
 '(modeline-mousable ((t (:background "DarkRed" :foreground "white"))))
 '(modeline-mousable-minor-mode ((t (:background "DarkRed" :foreground "white"))))
 '(muse-bad-link ((t (:foreground "#FF8882"))))
 '(muse-header-1 ((t (:foreground "#D6B163" :height 1.5 :inherit variable-pitch))))
 '(muse-header-2 ((t (:foreground "#A5F26E" :height 1.4 :inherit variable-pitch))))
 '(muse-header-3 ((t (:foreground "#4A77DE" :height 1.3 :inherit variable-pitch))))
 '(muse-header-4 ((t (:foreground "#529DB0" :height 1.2 :inherit variable-pitch))))
 '(muse-header-5 ((t (:foreground "#CC7832" :height 1.1 :inherit variable-pitch))))
 '(muse-link ((t (:foreground "#5DA8F6"))))
 '(muse-verbatim ((t (:foreground "#B150E7"))))
 '(nosci-fixme-face ((t (:background "#670000" :foreground "#ffffff" :bold t :box (:line-width 1 :color "#ff8e43")))) t)
 '(nosci-org-next-face ((t (:background "#4f97e9" :foreground "white" :box (:line-width 1 :style released-button)))) t)
 '(nosci-org-pending-face ((t (:background "#d85b00" :foreground "white" :box (:line-width 1 :style released-button)))) t)
 '(nosci-org-reading-face ((t (:background "#68527a" :foreground "white" :box (:line-width 1 :style released-button)))) t)
 '(nxml-attribute-local-name-face ((t (:inherit (quote font-lock-constant-face)))))
 '(nxml-attribute-value-delimiter-face ((t (:inherit (quote font-lock-string-face)))))
 '(nxml-attribute-value-face ((t (:inherit (quote font-lock-string-face)))))
 '(nxml-cdata-section-content-face ((t (:inherit (quote font-lock-string-face)))))
 '(nxml-comment-content-face ((t (:inherit (quote font-lock-comment-face)))))
 '(nxml-comment-delimiter-face ((t (:inherit (quote font-lock-comment-face)))))
 '(nxml-element-colon-face ((t (:bold t :foreground "#92D229"))))
 '(nxml-element-local-name-face ((t (:inherit (quote font-lock-function-name-face)))))
 '(nxml-element-prefix-face ((t (:bold t :foreground "#92D229"))))
 '(nxml-entity-ref-name-face ((t (:inherit (quote font-lock-constant-face)))))
 '(nxml-tag-delimiter-face ((t (:inherit (quote font-lock-function-name-face)))))
 '(nxml-tag-slash-face ((t (:inherit (quote font-lock-function-name-face)))))
 '(org-agenda-date ((t (:inherit font-lock-type-face))))
 '(org-agenda-date-weekend ((t (:inherit org-agenda-date))))
 '(org-column ((t (:background "#222222"))))
 '(org-column-title ((t (:background "DarkGreen" :foreground "white" :bold t :box (:line-width 1 :style released-button)))))
 '(org-date ((t (:inherit font-lock-constant-face))))
 '(org-done ((t (:background "DarkGreen" :foreground "white" :box (:line-width 1 :style released-button)))))
 '(org-hide ((t (:foreground "#191919"))))
 '(org-level-1 ((t (:inherit outline-1))))
 '(org-level-2 ((t (:inherit outline-2))))
 '(org-level-3 ((t (:inherit outline-3))))
 '(org-level-4 ((t (:inherit outline-4))))
 '(org-level-5 ((t (:inherit outline-5))))
 '(org-scheduled-previously ((t (:foreground "#d74b4b"))))
 '(org-scheduled-today ((t (:foreground "#ff6ab9" :italic t))))
 '(org-tag ((t (:inherit font-lock-comment-delimiter-face))))
 '(org-todo ((t (:background "DarkRed" :foreground "white" :box (:line-width 1 :style released-button)))))
 '(org-upcoming-deadline ((t (:foreground "#d6ff9c"))))
 '(org-warning ((t (:foreground "#8f6aff" :italic t))))
 '(outline-1 ((t (:foreground "#D6B163" :bold t))))
 '(outline-2 ((t (:foreground "#A5F26E" :bold t))))
 '(outline-3 ((t (:foreground "#B150E7" :bold nil))))
 '(outline-4 ((t (:foreground "#529DB0" :bold nil))))
 '(outline-5 ((t (:foreground "#CC7832" :bold nil))))
 '(region ((t :background "#505C74")))
 '(show-paren-match ((t (:background "#DA44FF" :foreground "#F6CCFF" :bold t))))
 '(text-cursor ((t (:background "yellow" :foreground "black"))))
 '(window-number-face ((t (:foreground "#FF7777")))))
