#!/usr/local/bin/zsh

zstyle ':completion:*' group-name ''
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s

#setopt list_packed      # compact completion lists
setopt list_types       # show types in completion

if type brew &>/dev/null; then
    FPATH=$(brew --prefix)/share/zsh-completions:$FPATH
fi

if [ -e "$HOME/.zsh-completions" ]; then
    FPATH="$HOME/.zsh-completions":$FPATH
fi

autoload -U compinit; compinit -u

# To get oh-my-zsh:
# git clone https://github.com/ohmyzsh/ohmyzsh.git $HOME/.oh-my-zsh
if [ -e "$HOME/.oh-my-zsh" ] ;  then
    plugins=(
        ant
        aws
        azure
        bundler
        docker
        docker-compose
        gcloud
        gh
        golang
        helm
        heroku
        iterm2
        kubectl
        minikube
        npm
        pass
        pip
        rails
        redis-cli
        rust
        screen
        svn
        terraform
        vscode
    )

    CASE_SENSITIVE=true
    source $HOME/.oh-my-zsh/oh-my-zsh.sh
fi
