#!/usr/local/bin/zsh

# Use Emacs style key bindings
bindkey -e

# PgUp - Search History previous
bindkey -$keymap '[5~'  'history-beginning-search-backward'
# PgDown - Search History next
bindkey -$keymap '[6~'  'history-beginning-search-forward'
